background            #140a0d
foreground            #d3c4db

# black
color0  #140a0d
color8  #6b6466

# red
color1  #a7756c
color9  #d1988c

# green
color2  #a67666
color10 #d09984

# yellow
color3  #b68575
color11 #e1a994

# blue
color4  #9aa5bb
color12 #bfcae7

# magenta
color5  #8c7c93
color13 #b29fbd

#cyan
color6  #879fae
color14 #aac5d8

#white
color7  #d3c4db
color15 #eac9fe
