# Background and foreground colors
background = #140a0d
foreground = #d3c4db

# Standard colors
palette = 0=#140a0d
palette = 1=#a7756c
palette = 2=#a67666
palette = 3=#b68575
palette = 4=#9aa5bb
palette = 5=#8c7c93
palette = 6=#879fae
palette = 7=#d3c4db

# Bright colors
palette = 8=#6b6466
palette = 9=#d1988c
palette = 10=#d09984
palette = 11=#e1a994
palette = 12=#bfcae7
palette = 13=#b29fbd
palette = 14=#aac5d8
palette = 15=#eac9fe
